# Generated by Django 5.0.7 on 2024-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TourHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='exclusions',
            field=models.ManyToManyField(to='tours.tourexclusion'),
        ),
        migrations.AddField(
            model_name='tour',
            name='highlights',
            field=models.ManyToManyField(to='tours.tourhighlight'),
        ),
        migrations.AddField(
            model_name='tour',
            name='inclusions',
            field=models.ManyToManyField(to='tours.tourinclusion'),
        ),
    ]
