# Generated by Django 5.0.7 on 2024-08-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourexclusion_tourhighlight_tourinclusion_tour_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(default='smth', unique=True),
            preserve_default=False,
        ),
    ]
