# Generated by Django 5.0.7 on 2024-08-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourcategory',
            options={'verbose_name_plural': 'Tour categories'},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='inclusions',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TourInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=128)),
                ('departure_time', models.TimeField()),
                ('return_time', models.TimeField()),
                ('exclusions', models.ManyToManyField(blank=True, to='tours.tourexclusion')),
                ('inclusions', models.ManyToManyField(blank=True, to='tours.tourinclusion')),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
    ]
