# Generated by Django 5.0.7 on 2024-08-14 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tourcategory_options_remove_tour_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourinfo',
            name='tour',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='tours.tour'),
        ),
    ]
