# Generated by Django 5.0.7 on 2024-08-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tourinfo_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_categories/'),
        ),
    ]
