# Generated by Django 5.0.7 on 2024-08-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_rename_image_tourcategory_background_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourcategory',
            old_name='fontawesome_icon',
            new_name='icon_class',
        ),
    ]
