# Generated by Django 5.0.7 on 2024-08-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_rename_fontawesome_icon_tourcategory_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourinfo',
            name='exclusions',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='tourinfo',
            name='inclusions',
        ),
        migrations.DeleteModel(
            name='TourExclusion',
        ),
        migrations.AddField(
            model_name='tourinfo',
            name='exclusions',
            field=models.TextField(default='smth'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TourHighlight',
        ),
        migrations.DeleteModel(
            name='TourInclusion',
        ),
        migrations.AddField(
            model_name='tourinfo',
            name='inclusions',
            field=models.TextField(default='smth'),
            preserve_default=False,
        ),
    ]
