# Generated by Django 5.0.7 on 2024-08-15 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_tourquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_pictures/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='tours.tour')),
            ],
        ),
    ]
